name: Exercise Feedback

on:
  push:
    branches:
      - main
    paths:
      - src/exercises/**

jobs:
  grading-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout exercise feedback
        uses: actions/checkout@v3
        with:
          repository: riehlegroup/adap-exercise-feedback
          path: main/src/tests

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      # Run grading feedback
      - name: Exercise feedback
        id: ex_feedback
        run: |
          main/src/tests/ci/run_grading.sh

      # Create badges
      - name: Create badges ex1
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: score_ex1
          LABEL: "Ex1"
          STATUS: ${{ steps.ex_feedback.outputs.score_ex1 }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create badges ex2
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: score_ex2
          LABEL: "Ex2"
          STATUS: ${{ steps.ex_feedback.outputs.score_ex2 }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create badges ex3
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: score_ex3
          LABEL: "Ex3"
          STATUS: ${{ steps.ex_feedback.outputs.score_ex3 }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create badges ex4
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: score_ex4
          LABEL: "Ex4"
          STATUS: ${{ steps.ex_feedback.outputs.score_ex4 }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create badges ex5
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: score_ex5
          LABEL: "Ex5"
          STATUS: ${{ steps.ex_feedback.outputs.score_ex5 }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create badges ex6
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: score_ex6
          LABEL: "Ex6"
          STATUS: ${{ steps.ex_feedback.outputs.score_ex6 }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}